// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHsJx7ZB0GOniT1ddy-MVpjGnQEkKQcbg',
    appId: '1:738543799106:web:1d1c8b5d8312915a8096db',
    messagingSenderId: '738543799106',
    projectId: 'techscope-4e85e',
    authDomain: 'techscope-4e85e.firebaseapp.com',
    storageBucket: 'techscope-4e85e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFNGLpFoMuKEWsOmgdDWIe-KlSzleuq5A',
    appId: '1:738543799106:android:d76717270c74decf8096db',
    messagingSenderId: '738543799106',
    projectId: 'techscope-4e85e',
    storageBucket: 'techscope-4e85e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-P-TpJRxyDLvhXkQQwf4mmRJD-skp270',
    appId: '1:738543799106:ios:e7df3d89a5e1c6498096db',
    messagingSenderId: '738543799106',
    projectId: 'techscope-4e85e',
    storageBucket: 'techscope-4e85e.firebasestorage.app',
    iosBundleId: 'com.example.techscope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-P-TpJRxyDLvhXkQQwf4mmRJD-skp270',
    appId: '1:738543799106:ios:e7df3d89a5e1c6498096db',
    messagingSenderId: '738543799106',
    projectId: 'techscope-4e85e',
    storageBucket: 'techscope-4e85e.firebasestorage.app',
    iosBundleId: 'com.example.techscope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHsJx7ZB0GOniT1ddy-MVpjGnQEkKQcbg',
    appId: '1:738543799106:web:321c87a3229c67298096db',
    messagingSenderId: '738543799106',
    projectId: 'techscope-4e85e',
    authDomain: 'techscope-4e85e.firebaseapp.com',
    storageBucket: 'techscope-4e85e.firebasestorage.app',
  );
}
